clone:
  depth: 1

options:
  docker: true

definitions:
  services:
    docker:
      memory: 2048

pipelines:
  default:
    - parallel:
        # build go app
        - step:
            name: go-test
            image: golang:1.11-stretch
            script:
              - |
                CGO_ENABLED=0
                GOOS=linux
                GOARCH=amd64
              - make devtools
              - make init
              - make build
              - make lint
              - make test
              - make cyclomatic
              # Ensure that `go mod tidy` does not change `go.sum` or `go.mod`.
              # `go mod tidy`: "add missing and remove unused modules".
              # If anything has changed, the diff will print it.
              - |
                go mod tidy
                git --no-pager diff
                [[ 0 -eq $(git status --porcelain go.sum go.mod | wc -l) ]]

        # lint and test the Vue.js app
        - step:
            name: web-lint-test
            image: node:8.11.1-slim
            # caches:
            #   - cache-web
            script:
              - cd web/
              - yarn install
              - yarn lint
              - yarn test:unit:coverage

        # build docker image
        - step:
            name: docker-image-build
            # caches:
            #   - docker
            script:
              - make build_image
              - docker images
