apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --verbose -f ./docker-compose.yml -o deploy/cluster/out/
    kompose.version: 1.15.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - image: mongo:3.6-jessie
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
      hostname: mongo
      nodeSelector:
        machine-size: medium
      restartPolicy: Always
status: {}
