apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --verbose -f ./docker-compose.yml -o deploy/cluster/out/
    kompose.version: 1.15.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ob-api-proxy
  name: ob-api-proxy
spec:
  ports:
  - name: "8003"
    port: 8003
    targetPort: 8003
  selector:
    io.kompose.service: ob-api-proxy
status:
  loadBalancer: {}
